@startuml
scale 800*600
hide empty description
skinparam componentStyle uml2

package "FSUIPC" {
    [FSUIPC offset change event]
    [FMGS offset set]
    package "LUA Script"{
        [ADIRS]
        [adirsDisplay]<<modules>>
        [battery]<<modules>>
        [handshake]<<modules>>
        [rotary]<<modules>>
        [sendReceiveData]<<modules>>
        [tripleGauge]<<modules>>
    }
    [FMGS offset set] <-- [rotary]
    [FSUIPC offset change event] --> [ADIRS]
}

package "Arduino" {
    [serialEvent]
    [setup]
    [loop]
}

[sendReceiveData] <-> USB
[loop] --> USB
USB --> [serialEvent]

@enduml