@startuml
scale 800*600
hide empty description
[*] --> State1
State1 : Rotary position unknown
State1 --> State2 : rcvRotaryPos
State2 : pending ADIRS update
State2 --> State3 : rotarySYSoff
State3 : ADIRS display off
State3 --> State2 : rcvRotaryPos
State2 --> State4 : sndADIRSInfo
State4 : wait for 'ACK'
State4 --> State2 : rcvNAK
State4 --> State2 : timeout
State4 --> State5 : rcvRotaryPos
State4 --> State5 : rcvFSUpdShown
State5 : unexpected change received
State5 --> State2 : rcvNAK
State5 --> State2 : rcvACK
State5 --> State2 : timeout
State5 --> State5 : rcvRotaryPos
State5 --> State5 : rcvFSUpdShown
State4 --> State6 : rcvACK
State6 : ADIRS display up to date
State6 --> State2 : rcvRotaryPos
State6 --> State2 : rcvFSUpdShown
State6 --> State3 : rotarySYSoff
}
@enduml